# This is a sample .pre-commit-config.yaml file
# Created using 'pre-commit sample-config'
# Copy this file to your project as .pre-commit-config.yaml to use pre-commit

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

# Additional recommended hooks
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
    -   id: shellcheck

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, chore, test]  # Restrict to our allowed types

# Custom local hooks
-   repo: local
    hooks:
    -   id: generate-changelog
        name: Generate changelog
        description: Automatically generates CHANGELOG.md using git-cliff
        entry: bash -c 'if command -v git-cliff >/dev/null 2>&1; then git-cliff --output CHANGELOG.md && git add CHANGELOG.md || exit 1; else echo "git-cliff not installed, skipping changelog generation"; fi'
        language: system
        pass_filenames: false
        stages: [push]
