#!/usr/bin/env bats
# pre-commit and prek are alternative git hook managers (same config, same
# hooks). Each has its own module; the git-hooks script installs the selected
# one and generates the global git template hooks with it.

setup() {
  load 'helpers/setup'

  TMPL=.chezmoiscripts/run_onchange_zzzzz_install-git-hooks.sh.tmpl
  SCRIPT_TARGET=.chezmoiscripts/zzzzz_install-git-hooks.sh
  STUBS="$BATS_TEST_TMPDIR/stubs"
  CALLS="$BATS_TEST_TMPDIR/calls"
  FAKE_HOME="$BATS_TEST_TMPDIR/home"
  mkdir -p "$STUBS" "$FAKE_HOME"
  : > "$CALLS"

  # uv only logs; prek and pre-commit write shims carrying their own marker,
  # like the real tools do.
  printf '#!/bin/sh\necho "uv $*" >> "%s"\n' "$CALLS" > "$STUBS/uv"
  cat > "$STUBS/prek" << EOF2
#!/bin/sh
echo "prek \$*" >> "$CALLS"
[ "\$1 \$2" = "util init-template-dir" ] || exit 0
dir=\$3; shift 3
mkdir -p "\$dir/hooks"
while [ \$# -gt 0 ]; do
  printf '#!/bin/sh\n# File generated by prek: https://github.com/j178/prek\n' > "\$dir/hooks/\$2"
  shift 2
done
EOF2
  cat > "$STUBS/pre-commit" << EOF2
#!/bin/sh
echo "pre-commit \$*" >> "$CALLS"
[ "\$1" = "init-templatedir" ] || exit 0
shift
hooks=""
while [ \$# -gt 1 ]; do hooks="\$hooks \$2"; shift 2; done
dir=\$1
mkdir -p "\$dir/hooks"
for h in \$hooks; do
  printf '#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\n' > "\$dir/hooks/\$h"
done
EOF2
  chmod +x "$STUBS"/*
}

# render_script MODULES_JSON — render the git-hooks script for the modules.
render_script() {
  local h
  h=$(mk_fake_home "$BATS_TEST_TMPDIR/cfg")
  seed_chezmoi_config "$h" "{\"modules\":$1}"
  chezmoi_render "$h" "$TMPL" > "$BATS_TEST_TMPDIR/hooks.sh"
}

# run_script [PATH_PREFIX] — run the rendered script against the fake home.
run_script() {
  run env -i PATH="${1:-$STUBS}:/usr/bin:/bin" HOME="$FAKE_HOME" sh "$BATS_TEST_TMPDIR/hooks.sh"
}

gen_calls() { grep -cE '^(prek util init-template-dir|pre-commit init-templatedir)' "$CALLS" || true; }

@test "packages.yaml defines both modules and python_dev no longer installs pre-commit" {
  yq -e '.packages.darwin.modules | (has("pre_commit") and has("prek"))' "$REPO_ROOT/.chezmoidata/packages.yaml"
  ! grep -n 'pre-commit' "$REPO_ROOT/.chezmoiscripts/run_onchange_zzzzz_install-python-tools.sh"
}

@test "the init prompt offers both modules" {
  prompt_module_names | grep -qx pre_commit
  prompt_module_names | grep -qx prek
}

@test "the git-hooks script is managed only with pre_commit or prek" {
  for modules in '[]' '["python_dev"]' '["atuin"]'; do
    H=$(mk_fake_home "$BATS_TEST_TMPDIR/off")
    seed_chezmoi_config "$H" "{\"modules\":$modules}"
    if chezmoi_managed_with_scripts "$H" | grep -qxF "$SCRIPT_TARGET"; then return 1; fi
  done
  for modules in '["pre_commit"]' '["prek"]' '["pre_commit","prek"]'; do
    H=$(mk_fake_home "$BATS_TEST_TMPDIR/on")
    seed_chezmoi_config "$H" "{\"modules\":$modules}"
    chezmoi_managed_with_scripts "$H" | grep -qxF "$SCRIPT_TARGET"
  done
}

@test "the python-tools script is still gated on python_dev alone" {
  H=$(mk_fake_home "$BATS_TEST_TMPDIR/pre")
  seed_chezmoi_config "$H" '{"modules":["pre_commit","prek"]}'
  ! chezmoi_managed_with_scripts "$H" | grep -qxF .chezmoiscripts/zzzzz_install-python-tools.sh
}

@test "every rendered variant passes shellcheck" {
  command -v shellcheck > /dev/null 2>&1 || skip "shellcheck not available"
  for modules in '["pre_commit"]' '["prek"]' '["pre_commit","prek"]'; do
    render_script "$modules"
    shellcheck "$BATS_TEST_TMPDIR/hooks.sh"
  done
}

@test "prek: installs prek with uv and generates the template hooks with it" {
  render_script '["prek"]'
  run_script
  [ "$status" -eq 0 ]
  grep -qxF 'uv tool install --upgrade prek' "$CALLS"
  grep -qxF "prek util init-template-dir $FAKE_HOME/.git_template -t commit-msg -t pre-commit -t pre-push" "$CALLS"
  if grep -q '^pre-commit ' "$CALLS"; then return 1; fi
  for h in commit-msg pre-commit pre-push; do
    grep -q 'File generated by prek' "$FAKE_HOME/.git_template/hooks/$h"
  done
}

@test "pre_commit: installs pre-commit with uv and generates the template hooks with it" {
  render_script '["pre_commit"]'
  run_script
  [ "$status" -eq 0 ]
  grep -qxF 'uv tool install --upgrade pre-commit' "$CALLS"
  grep -qxF "pre-commit init-templatedir -t commit-msg -t pre-commit -t pre-push $FAKE_HOME/.git_template" "$CALLS"
  if grep -q '^prek ' "$CALLS"; then return 1; fi
  for h in commit-msg pre-commit pre-push; do
    grep -q 'File generated by pre-commit' "$FAKE_HOME/.git_template/hooks/$h"
  done
}

@test "both selected: prek is used" {
  render_script '["pre_commit","prek"]'
  run_script
  [ "$status" -eq 0 ]
  grep -qxF 'uv tool install --upgrade prek' "$CALLS"
  ! grep -q '^pre-commit ' "$CALLS"
}

@test "a second run regenerates nothing" {
  render_script '["prek"]'
  run_script
  [ "$(gen_calls)" = "1" ]
  run_script
  [ "$status" -eq 0 ]
  [ "$(gen_calls)" = "1" ]
}

@test "switching tools replaces the other tool's shims" {
  render_script '["pre_commit"]'
  run_script
  render_script '["prek"]'
  run_script
  [ "$status" -eq 0 ]
  for h in commit-msg pre-commit pre-push; do
    grep -q 'File generated by prek' "$FAKE_HOME/.git_template/hooks/$h"
    if grep -q 'File generated by pre-commit' "$FAKE_HOME/.git_template/hooks/$h"; then return 1; fi
  done
}

@test "a hook the user wrote is left alone" {
  mkdir -p "$FAKE_HOME/.git_template/hooks"
  printf '#!/bin/sh\necho mine\n' > "$FAKE_HOME/.git_template/hooks/pre-commit"
  render_script '["prek"]'
  run_script
  [ "$status" -eq 0 ]
  [ "$(cat "$FAKE_HOME/.git_template/hooks/pre-commit")" = "$(printf '#!/bin/sh\necho mine')" ]
  grep -q 'File generated by prek' "$FAKE_HOME/.git_template/hooks/commit-msg"
  [[ "$output" == *"not a generated hook"* ]]
}

@test "without uv the script fails with a clear message" {
  render_script '["prek"]'
  rm "$STUBS/uv"
  run_script
  [ "$status" -ne 0 ]
  [[ "$output" == *"uv is required"* ]]
}

@test "README lists both modules as alternatives and python_dev without pre-commit" {
  grep -qE '^\| `pre_commit` \|.*Alternative to prek: pick one' "$REPO_ROOT/README.md"
  grep -qE '^\| `prek` \|.*Alternative to pre_commit: pick one' "$REPO_ROOT/README.md"
  ! grep -E '^\| `python_dev` \|' "$REPO_ROOT/README.md" | grep -q 'pre-commit'
}

@test "prek accepts this repo's pre-commit config" {
  command -v prek > /dev/null 2>&1 || skip "prek not installed"
  prek validate-config "$REPO_ROOT/.pre-commit-config.yaml"
}
